config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about"
  resources :users, only: [:index, :show, :edit, :update]
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  attachment :profile_image

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    added_attrs = [:name, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

   def create
     @book = Book.find(params[:book_id])
     @comment = BookComment.new(book_comment_params)
     @comment.user_id = current_user.id
     @comment.book_id = @book.id
     @comment.save
     render :index
   end

   def destroy
      @book = Book.find(params[:book_id])
      @comment = BookComment.find_by(id: params[:id], book_id: params[:book_id])
      @comment.destroy
      render :index
   end

   private

   def book_comment_params
      params.require(:book_comment).permit(:comment)
   end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @book = Book.new
    @user = User.find(current_user.id)
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @user = User.find(current_user.id)
      @books = Book.all
      render :index
    end
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = User.find(@book.user.id)
    @comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      @book = Book.find(params[:id])
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end


  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.reverse_order
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      @user = User.find(params[:id])
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_comment-form.html.erb
  <%= form_with(model:[book, comment], remote: true) do |f| %>
    <%= f.text_area :comment, rows:"5", class:"col-8", id: "text_area" %>
    <%= f.submit "送信する" %>
  <% end %>

app/views/book_comments/_comment-index.html.erb
<table>
  <% book.book_comments.each do |book_comment| %>
  <div class="comment_<%= book_comment.id %>">
    <tr>
      <td>
        <p><%= image_tag("no_image.jpg") %></p>
        <%= link_to "#{book_comment.user.name}", user_path(book_comment.user_id) %>
      </td>
      <td>
        <%= book_comment.comment %>
      </td>
      <td>
        <% if current_user.id == book_comment.user_id %>
          <%= link_to "Destroy", book_book_comment_path(book_comment.book_id, book_comment.id), method: :delete, remote: true %>
        <% end %>
      </td>
    <% end %>
  </tr>
  </div>
</table>

app/views/book_comments/create.js.erb
$(".comment-index-<%= @book %>").html("<%= j(render partial: "book_comments/comment-index", locals: {book: @book, comment: @comment})%>");
$("textarea").val("");

app/views/book_comments/destroy.js.erb
$(".comment-index-<%= @book %>").html("<%= j(render partial: "book-comments/comment-index", locals: {book: @book, comment: @comment}) %>");
$("textarea").val("");

app/views/book_comments/index.js.erb
$(".comment-index").html("<%= j(render partial: "comment-index", locals: {book: @book}) %>");
$("#text_area").val("");

app/views/books/_error.html.erb
  <% if book.errors.any? %>
    <h4 class="error"><%= pluralize(book.errors.count, "error") %> prohidited this product from being saved:</h4>
    <ul class="error pl-5">
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

app/views/books/_list.html.erb
<div class="row">
  <div class="pl-4">
    <h2>Books</h2>
    <table class="table mt-3">
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
      </tr>
      <% books.each do |book| %>
        <tr>
          <td><%= link_to user_path(book.user.id) do %>
          <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
          <% end %></td>
          <td><%= link_to book.title, book_path(book.id) %></td>
          <td><%= book.body %></td>
          <td class="favorites-btn-<%= book.id %>">
            <%= render partial: "favorites/favorites-btn", locals: { book: book} %>
          </td>
          <td>
            <p>コメント数: <%= book.book_comments.count %></p>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/books/_new.html.erb
  <div class="row">
    <div class="mx-auto mt-4">
      <h2>New book</h2>
      <%= form_with model: book, url:"/books", local:true do |f| %>
        <p>Title</p>
        <%= f.text_field :title, class: "field" %>
        <p>Opinion</p>
        <%= f.text_area :body, class: "field" %>
        <%=f.submit "Create Book", class: "btn btn-info" %>
      <% end %>
    </div>
  </div>

app/views/books/edit.html.erb
<div class="row">
  <div class="mx-auto pt-3">
  <h1>Editing Book</h1>
  <%= form_with model:@book, local:true do |f| %>
  <% if @book.errors.any? %>
    <h4 class="error"><%= pluralize(@book.errors.count, "error") %> prohidited this product from being saved:</h4>
    <ul class="error pl-5">
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
    <h4>Title</h4>
    <%= f.text_field :title, class: "field" %>
    <h4>Opinion</h4>
    <%= f.text_area :body, class: "field" %>
    <%= f.submit "Update Book", class: "btn btn-success mt-2" %>
  <% end %>
  <p class="mt-4"><%= link_to "Show", book_path(@book.id) %> | <%= link_to "Back", books_path %></p>
  </div>
</div>

app/views/books/index.html.erb
<div class="row">
  <div class="pt-1">

    <%= render "books/error", book: @book %>

  </div>
</div>
<div class="row pt-3">
  <div class="col-md-3">

    <%= render "users/user", user: @user %>

    <%= render "books/new", book: @book %>

  </div>
  <div class="col-md-8 offset-md-1">

    <%= render "books/list", books: @books %>
  </div>
</div>

app/views/books/new.html.erb
<h1>New book</h1>
<%= form_with model: @book, local:true do |f| %>
  <% if @book.errors.any? %>
    <%= @book.errors.count %> prohidited this product from being saved:
    <% @book.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%=f.submit "Create Book" %>
<% end %>

app/views/books/show.html.erb
<div class="row pt-3">
  <div class="col-md-3">

    <%= render "users/user", user: @user %>

    <%= render "books/new", book: @book_new %>

  </div>
  <div class="col-md-8 offset-md-1">
    <h1>Book detail</h1>
    <table class="table">
      <tr>
        <td><%= link_to user_path(@book.user.id) do %>
          <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg" %>
          <p><%= @book.user.name %></p>
        <% end %></td>
        <td><%= @book.title %></td>
        <td><%= @book.body %></td>
        <td class="favorites-btn-<%= @book.id %>">
          <%= render partial: "favorites/favorites-btn", locals: { book: @book} %>
        </td>
        <td>
          <p>コメント数: <%= @book.book_comments.count %></p>
        </td>
        <% if @book.user == current_user %>
          <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-success" %></td>
          <td><%= link_to "Destroy", book_path(@book), class: "btn btn-danger", method: :delete, data: {confirm: "本当に削除？"} %></td>
        <% end %>
      </tr>
    </table>
    <div class="comment-index">
      <%= render partial: "book_comments/comment-index", locals: { book: @book } %>
    </div>
      <%= render partial: "book_comments/comment-form", locals: { book: @book, comment: @comment } %>

  </div>
</div>

app/views/favorites/_favorites-btn.html.erb
<% if book.favorited_by?(current_user) %>
  <p>
    <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
      <i class="fas fa-heart"></i><%= book.favorites.count %>
    <% end %>
  </p>
<% else %>
  <p>
    <%= link_to book_favorites_path(book), method: :post, remote: true do %>
      <i class="far fa-heart"></i><%= book.favorites.count %>
    <% end %>
  </p>
<% end %>

app/views/favorites/create.js.erb
$(".favorites-btn-<%= @book.id %>").html("<%= j(render partial: 'favorites/favorites-btn', locals: {book: @book}) %>");

app/views/favorites/destroy.js.erb
$('.favorites-btn-<%= @book.id %>').html("<%= j(render partial: 'favorites/favorites-btn', locals: {book: @book}) %>");

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto pt-3">
      <h1>Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
 <div class="row">
   <div class="pt-3 mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
     <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
     <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
     <p>you can share and exchange your opinions , inpressions , and emotions</p>
     <p> about various books!</p>
     <div class="btn-wrapper col-8 mx-auto">
       <div class="row">
         <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
       </div>
       <div class="row">
         <%= link_to "Sign Up",new_user_registration_path, class: "btn btn-success btn-sm btn-block mb-5 sign_up" %>
       </div>
     </div>
   </div>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=devuxe-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/0c03b7e0c7.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">Bookers</a>
          <button class="navbar-toggler" type="botton" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation" >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to  user_path(current_user.id), class: "nav-link text-light" do %>
                    <i class="fas fa-home"></i>Home
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to users_path, class: "nav-link text-light" do %>
                    <i class="fas fa-users"></i>Users
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to books_path, class: "nav-link text-light" do %>
                    <i class="fas fa-book-open"></i>Books
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
                    <i class="fas fa-sign-out-alt"></i>logout
                  <% end %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to root_path, class: "nav-link text-light" do %>
                    <i class="fas fa-home"></i>Home
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to home_about_path, class: "nav-link text-light" do %>
                    <i class="fas fa-link"></i>About
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
                    <i class="fas fa-user-plus"></i>sign up
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_session_path, class: "nav-link text-light" do %>
                    <i class="fas fa-sign-in-alt"></i>login
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <div class="container">
        <div class="row">
          <div class="px-5">
            <% flash.each do |message_type, message| %>
              <%= content_tag :div, message, class: message_type %>
            <% end %>
          </div>
        </div>

      <%= yield %>
      </div>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_user.html.erb
  <div class="row">
    <div class="mx-auto">
      <h2>User info</h2>

      <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: "jpeg", fallback: "no_image.jpg" %>
      <table class="table mt-3">
        <tr>
          <td>name</td>
          <td><%= user.name %></td>
        </tr>
        <tr>
          <td>introduction</td>
          <td><%= user.introduction %></td>
        </tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="mx-auto mt-1">
        <%= link_to edit_user_path(user.id) do %>
          <i class="fas fa-user-cog btn btn-outline-secondary px-5"></i>
      <% end %>
    </div>
  </div>

app/views/users/edit.html.erb
<div class="row">
  <div class="mx-auto pt-3">
    <h1>User info</h1>
    <%= form_with model:@user, local:true do |f| %>
      <% if @user.errors.any? %>
      <h4 class="error"><%= pluralize(@user.errors.count, "error") %> prohidited this product from being saved:</h4>
      <ul class="error pl-5">
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  <p>Name</p>
  <%= f.text_field :name, autofocus: true, class: "field mb-4" %>
  <p>Image</p>
  <%= f.attachment_field :profile_image, placeholder: "Image", class: "mb-4" %>
  <p>Introduction</p>
  <%= f.text_area :introduction, class: "field mb-3" %>
  <%= f.submit "Update User", class: "btn btn-secondary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
<div class="row">
  <div class="col-md-3">

    <%= render "users/user", user: @user %>

    <%= render "books/new", book: @book %>

  </div>
  <div class="col-md-8 offset-md-1">
    <div class="row">
      <div class="pt-4">
        <h1>Users</h1>
        <table class="table mt-3 ">
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
          <% @users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user.id) %></td>
          </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-3">

    <%= render "users/user", user: @user %>

    <%= render "books/new", book: @book %>

  </div>
  <div class="col-md-8 offset-md-1">

    <%= render "books/list", books: @books %>
  </div>
</div>